FileVersion = 1
Projects = {PortalEmulator = {Path = "./PortalEmulator"}, Sizzle = {Path = "./Sizzle"}, "SDL3-Beef.git" = {Git = "https://github.com/jayrulez/SDL3-Beef.git"}, SDL3_shadercross-Beef = {Git = "https://github.com/jayrulez/SDL3_shadercross-Beef"}, Benchmarks = {Path = "./Benchmarks"}, Beef-Assimp = {Path = "./Beef-Assimp"}}

[Workspace]
StartupProject = "PortalEmulator"

[Configs.Release.Win64]
BfSIMDSetting = "AVX"
